# Generated by Django 3.2.4 on 2023-05-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20230502_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='workTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('workType', models.CharField(choices=[('Y', 'Youtube'), ('I', 'Instagram'), ('O', 'Other')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='artistTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('work', models.ManyToManyField(to='mainapp.workTable')),
            ],
        ),
    ]
